apiVersion: v1
kind: Secret
metadata:
  name: photo-secret
  namespace: praveen-ns 
stringData:
  MONGODB_URI: "mongodb://mongo-service:27017/"
  MONGODB_AUTH_URI: "mongodb://mongo-service:27017/artgallery"
  MONGODB_FEEDBACK_URI: "mongodb://mongo-service:27017/artgallery"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-deploy 
  namespace: praveen-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: photo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: photo
    spec:
      nodeSelector:
        worker: node1
      containers:
        - name: photo-container 
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
          image: praveenx03/photo-studio:v1.1.0
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: photo-secret
                  key: MONGODB_URI
            - name: MONGODB_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: photo-secret
                  key: MONGODB_AUTH_URI
            - name: MONGODB_FEEDBACK_URI
              valueFrom:
                secretKeyRef:
                  name: photo-secret
                  key: MONGODB_FEEDBACK_URI
            



---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
  namespace: praveen-ns
spec:
  selector:
    app: photo
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
