apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: photo-deploy-hpa
  namespace: praveen-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: photo-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: 5



