apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8slatestimages
spec:
  crd:
    spec:
      names:
        kind: K8sLatestImages
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredresources
 
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          endswith(container.image,":latest")
          msg := sprintf("Container %v must not have latest image", [container.name])
        }

       